/**
 * Generates project.yaml — the bridge between Architect and Developer
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import yaml from 'js-yaml';

/**
 * @param {object} config - Configuration from wizard
 * @param {object} opts - { dryRun: boolean }
 */
export async function generateProjectYaml(config, opts = {}) {
  const outputPath = resolve(config.cwd, 'project.yaml');

  const projectYaml = {
    project: {
      name: config.project.name,
      organization: config.project.organization,
      description: config.project.description,
      confluence: config.project.confluence,
    },
    fronts: config.fronts.map((front) => ({
      name: front.name,
      description: front.description,
      repos: front.repos,
    })),
    conventions: {
      default_branch: config.conventions.defaultBranch,
      commit_format: config.conventions.commitFormat,
      coding_standards: config.conventions.codingStandards,
      test_strategy: config.conventions.testStrategy,
    },
    team: {
      members: config.team.members.map((m) => ({
        name: m.name,
        slug: m.slug,
        description: m.description,
        repoKey: m.repoKey,
        color: m.color,
      })),
    },
  };

  const content = `# project.yaml — Generated by DevCrew (${config.mode} mode)
# This file describes the project context for AI team setup.
# Share this file with your team so they can run: devcrew init
#
# Generated: ${new Date().toISOString()}

${yaml.dump(projectYaml, { lineWidth: 120, noRefs: true })}`;

  if (opts.dryRun) {
    return { preview: outputPath };
  }

  writeFileSync(outputPath, content, 'utf-8');
  return { path: outputPath };
}
