/**
 * Generates project.yaml — the bridge between Architect and Developer
 *
 * Serializes the new V0 config structure:
 *   project (with context minus extracted), repos, conventions, agents
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import yaml from 'js-yaml';

/**
 * @param {object} config - Configuration from wizard (V0 shape)
 * @param {object} opts - { dryRun: boolean }
 */
export async function generateProjectYaml(config, opts = {}) {
  const outputPath = resolve(config.cwd, 'project.yaml');

  // Build the context object, excluding `extracted` (runtime-only data)
  const context = {};
  if (config.project.context) {
    const ctx = config.project.context;
    if (ctx.confluenceUrl) context.confluenceUrl = ctx.confluenceUrl;
    if (ctx.manual) context.manual = ctx.manual;
    if (ctx.files && ctx.files.length > 0) context.files = ctx.files;
    if (ctx.businessRules) context.businessRules = ctx.businessRules;
    if (ctx.technicalRules) context.technicalRules = ctx.technicalRules;
  }

  const projectYaml = {
    project: {
      name: config.project.name,
      organization: config.project.organization,
      description: config.project.description,
      ...(Object.keys(context).length > 0 ? { context } : {}),
    },
    repos: config.repos.map((r) => ({
      name: r.name,
      path: r.path,
      stack: r.stack,
      package_manager: r.package_manager,
    })),
    conventions: {
      default_branch: config.conventions.defaultBranch,
      commit_format: config.conventions.commitFormat,
      coding_standards: config.conventions.codingStandards,
      test_strategy: config.conventions.testStrategy,
    },
    agents: config.agents.map((a) => ({
      name: a.name,
      slug: a.slug,
      description: a.description,
      role: a.role,
      color: a.color,
    })),
  };

  const content = `# project.yaml — Generated by DevCrew (${config.mode} mode)
# This file describes the project context for AI team setup.
# Share this file with your team so they can run: devcrew init
#
# Generated: ${new Date().toISOString()}

${yaml.dump(projectYaml, { lineWidth: 120, noRefs: true })}`;

  if (opts.dryRun) {
    return { preview: outputPath };
  }

  writeFileSync(outputPath, content, 'utf-8');
  return { path: outputPath };
}
