/**
 * Developer Wizard — Consumer mode
 *
 * Reads project.yaml generated by the Architect/Tech Lead,
 * asks the developer which front they're working on,
 * and collects local repo paths.
 */

import { readFileSync } from 'node:fs';
import inquirer from 'inquirer';
import chalk from 'chalk';
import yaml from 'js-yaml';

/**
 * @param {string} cwd - Current working directory
 * @param {string} projectYamlPath - Path to project.yaml
 * @returns {object|null} Config object or null if cancelled
 */
export async function developerWizard(cwd, projectYamlPath) {
  let projectConfig;
  try {
    const raw = readFileSync(projectYamlPath, 'utf-8');
    projectConfig = yaml.load(raw);
  } catch (err) {
    console.log(chalk.red(`\n✖ Failed to read project.yaml: ${err.message}`));
    return null;
  }

  const { project, fronts, conventions, team } = projectConfig;

  console.log(`  Project: ${chalk.bold(project.name)}`);
  console.log(`  Organization: ${project.organization}`);
  console.log(`  Fronts: ${fronts.length} (${fronts.map((f) => f.name).join(', ')})`);
  console.log(`  Team: ${team.members.length} members (${team.members.map((m) => m.name).join(', ')})\n`);

  // ── Select front ───────────────────────────────────────────────────
  let selectedFront;

  if (fronts.length === 1) {
    selectedFront = fronts[0];
    console.log(`  Using front: ${chalk.bold(selectedFront.name)}\n`);
  } else {
    const { frontIndex } = await inquirer.prompt([
      {
        type: 'list',
        name: 'frontIndex',
        message: 'Which front are you working on?',
        choices: fronts.map((f, i) => ({
          name: `${f.name}${f.description ? ` — ${f.description}` : ''}`,
          value: i,
        })),
      },
    ]);
    selectedFront = fronts[frontIndex];
  }

  // ── Collect local repo paths ───────────────────────────────────────
  console.log(chalk.dim(`\nPoint to your local repositories for "${selectedFront.name}":\n`));

  const localRepos = [];
  for (const repo of selectedFront.repos) {
    const { localPath } = await inquirer.prompt([
      {
        type: 'input',
        name: 'localPath',
        message: `${repo.name} repo local path (${repo.path}):`,
        default: repo.path,
        validate: (v) => v.trim().length > 0 || 'Path is required',
      },
    ]);

    localRepos.push({
      ...repo,
      localPath: localPath.trim(),
    });
  }

  // ── Build config ───────────────────────────────────────────────────
  const config = {
    mode: 'developer',
    cwd,
    project: {
      name: project.name,
      organization: project.organization,
      description: project.description,
      confluence: project.confluence || null,
    },
    fronts: [
      {
        ...selectedFront,
        repos: localRepos,
      },
    ],
    selectedFront: selectedFront.name,
    conventions: conventions || {
      defaultBranch: 'develop',
      commitFormat: 'conventional',
      codingStandards: [],
      testStrategy: 'unit + integration',
    },
    team: team || {
      members: [{ name: 'Tech Lead', slug: 'tech-lead', description: 'Orchestrator', repoKey: null, color: '#AF52DE' }],
    },
  };

  // ── Confirmation ───────────────────────────────────────────────────
  console.log(chalk.bold('\nDevCrew will generate for "' + selectedFront.name + '":\n'));
  console.log(`  📁 ${chalk.cyan('CLAUDE.md')}               — Project context`);
  console.log(`  📁 ${chalk.cyan('.claude/agents/')}         — ${config.team.members.length} agent definitions`);
  console.log(`  📁 ${chalk.cyan('.claude/WORKFLOW.md')}     — Team topology`);
  console.log(`  📁 ${chalk.cyan('.claude/settings.json')}   — Permissions`);
  console.log(`  📁 ${chalk.cyan('Maestri workspace')}       — "${project.name} — ${selectedFront.name}"`);

  const repoSummary = localRepos
    .map((repo) => `    ${repo.name}: ${repo.localPath} (${repo.stack})`)
    .join('\n');
  console.log(`\n  Repositories:\n${repoSummary}`);

  const { proceed } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'proceed',
      message: '\nProceed?',
      default: true,
    },
  ]);

  return proceed ? config : null;
}
