/**
 * Developer Wizard — Consumer mode
 *
 * Reads project.yaml generated by the Architect/Tech Lead,
 * confirms/updates local repo paths, and builds the config object
 * using the new V0 data model.
 *
 * Key changes from old model:
 *   - No more "select front" — the workspace is the same for everyone
 *   - Reads repos[] instead of fronts[]
 *   - Reads agents[] instead of team.members[]
 *   - Reads project.context for Confluence/manual context
 */

import { readFileSync } from 'node:fs';
import inquirer from 'inquirer';
import chalk from 'chalk';
import yaml from 'js-yaml';

/**
 * @param {string} cwd - Current working directory
 * @param {string} projectYamlPath - Path to project.yaml
 * @returns {object|null} Config object or null if cancelled
 */
export async function developerWizard(cwd, projectYamlPath) {
  let projectConfig;
  try {
    const raw = readFileSync(projectYamlPath, 'utf-8');
    projectConfig = yaml.load(raw);
  } catch (err) {
    console.log(chalk.red(`\n✖ Failed to read project.yaml: ${err.message}`));
    return null;
  }

  const { project, repos, conventions, agents } = projectConfig;

  // ── Show project overview ────────────────────────────────────────────
  console.log(`  Project: ${chalk.bold(project.name)}`);
  console.log(`  Organization: ${project.organization}`);
  console.log(`  Repos: ${repos.length} (${repos.map((r) => r.name).join(', ')})`);
  console.log(`  Agents: ${agents.length} (${agents.map((a) => a.name).join(', ')})\n`);

  if (project.context?.confluenceUrl) {
    console.log(`  📎 Confluence: ${chalk.dim(project.context.confluenceUrl)}`);
  }
  if (project.context?.manual) {
    const preview = project.context.manual.substring(0, 60);
    console.log(`  📝 Context: ${chalk.dim(preview + (project.context.manual.length > 60 ? '...' : ''))}`);
  }
  console.log('');

  // ── Confirm/update local repo paths ────────────────────────────────
  console.log(chalk.dim('Confirm or update local repository paths:\n'));

  const localRepos = [];
  for (const repo of repos) {
    const { localPath } = await inquirer.prompt([
      {
        type: 'input',
        name: 'localPath',
        message: `${repo.name} (${repo.stack}) local path:`,
        default: repo.path,
        validate: (v) => v.trim().length > 0 || 'Path is required',
      },
    ]);

    localRepos.push({
      ...repo,
      path: localPath.trim(),
    });
  }

  // ── Build config ───────────────────────────────────────────────────
  const config = {
    mode: 'developer',
    cwd,
    project: {
      name: project.name,
      organization: project.organization,
      description: project.description,
      context: project.context || {
        confluenceUrl: null,
        extracted: [],
        manual: '',
        files: [],
        businessRules: '',
        technicalRules: '',
      },
    },
    repos: localRepos,
    conventions: conventions || {
      defaultBranch: 'develop',
      commitFormat: 'conventional',
      codingStandards: [],
      testStrategy: 'unit + integration',
    },
    agents: agents || [
      {
        name: 'Tech Lead',
        slug: 'tech-lead',
        description: 'Orchestrates all work, delegates to sub-agents, coordinates the full pipeline',
        role: 'orchestrator',
        color: '#AF52DE',
      },
    ],
  };

  // ── Confirmation ───────────────────────────────────────────────────
  console.log(chalk.bold('\nDevCrew will generate:\n'));
  console.log(`  📁 ${chalk.cyan('CLAUDE.md')}               — Project context for all agents`);
  console.log(`  📁 ${chalk.cyan('.claude/WORKFLOW.md')}     — Team topology and delegation rules`);
  console.log(`  📁 ${chalk.cyan('.claude/settings.json')}   — Permissions and config`);
  console.log(`  📁 ${chalk.cyan('.claude/agents/')}         — ${config.agents.length} agent definitions`);
  console.log(`  📁 ${chalk.cyan('Maestri workspace')}       — Connected terminals`);

  const repoSummary = localRepos
    .map((repo) => `    ${repo.name}: ${repo.path} (${repo.stack}, ${repo.package_manager})`)
    .join('\n');
  console.log(`\n  Repositories:\n${repoSummary}`);

  // Show agent topology
  const roleIcons = {
    orchestrator: '🟣',
    executor: '🟢',
    validator: '🔵',
    monitor: '🔴',
  };

  console.log('\n  Agents:');
  for (const agent of config.agents) {
    const icon = roleIcons[agent.role] || '⚪';
    console.log(`    ${icon} ${agent.name} (${agent.role})`);
  }

  const { proceed } = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'proceed',
      message: '\nProceed with generation?',
      default: true,
    },
  ]);

  return proceed ? config : null;
}
